"""
Affordance data structures for the ToolManip framework — Module II.

Maps to paper Section 3.3:
  - KeypointResult: H, F, τt, O, Q, τo  (Eq. 4/5 affordance keypoints)
  - PixelCoordinate: resolved pixel + normalized coordinate
  - AffordanceCoordinates: full spatial result for robot execution
  - AffordanceResult: full affordance reasoning output per task

Reference: Zhou et al., "Towards zero-shot robot tool manipulation in
industrial context", Robotics and Computer-Integrated Manufacturing 98 (2026).
"""

from dataclasses import dataclass
from typing import List, Optional


class AffordanceResolutionError(Exception):
    """
    Raised when the VLM's affordance output cannot be resolved to real
    coordinates — a missing label, a non-numeric label, a label outside the
    candidate set generated by SIF, or a degenerate O==Q operation vector.

    This is deliberately fatal. Substituting a placeholder (e.g. the image
    centre) produces a result file that looks valid but encodes nothing, which
    silently corrupts any downstream keypoint-error measurement.
    """


@dataclass
class KeypointResult:
    """
    Affordance keypoints selected by the VLM from annotated images.

    Paper Section 3.3.2:
      H  — grasp point on the tool (where gripper holds)
      F  — functional point on the tool (working surface extreme edge)
      τt — tool operational direction vector at F
      O  — start contact point on the target object
      Q  — end point on target where the operation stops
      τo — motion/force direction along the target surface

    A field is None when that label was absent from the VLM's response.
    None is preserved rather than defaulted so the failure stays visible.
    """
    grasp_point: Optional[str]        # H — dot label on tool image
    functional_point: Optional[str]   # F — dot label on tool image
    tool_direction: Optional[str]     # τt — direction label on tool
    start_point: Optional[str]        # O — dot label on target image
    end_point: Optional[str]          # Q — dot label on target image
    target_direction: Optional[str]   # τo — direction label on target


@dataclass
class PixelCoordinate:
    u: int                  # pixel x (horizontal, left=0)
    v: int                  # pixel y (vertical, top=0)
    u_norm: float           # normalized 0.0-1.0 (u/image_width)
    v_norm: float           # normalized 0.0-1.0 (v/image_height)
    image_width: int
    image_height: int

    def to_dict(self) -> dict:
        return {
            "pixel": [self.u, self.v],
            "normalized": [round(self.u_norm, 4), round(self.v_norm, 4)],
            "image_size": [self.image_width, self.image_height],
            "note": "3D conversion pending camera calibration"
        }


@dataclass
class AffordanceCoordinates:
    """
    All resolved spatial information from affordance reasoning.
    Pixel coordinates are in ROI image space (after HRE crop).
    Normalized coordinates are hardware-ready for camera projection.
    When depth camera available:
      X = (u - cx) * Z / fx
      Y = (v - cy) * Z / fy
      Z = depth_value at pixel (u, v)
    """
    grasp_point_H: PixelCoordinate
    functional_point_F: PixelCoordinate
    tool_direction_angle: float       # degrees, 0=right, 90=down
    start_point_O: PixelCoordinate
    end_point_Q: PixelCoordinate
    target_direction_angle: float     # degrees
    operation_distance_px: float      # pixel distance O→Q
    operation_vector: list            # [dx, dy] unit vector O→Q


@dataclass
class AffordanceResult:
    """
    Full affordance reasoning output produced by Module II.

    Consumed by Module III (Motion and Force Primitive Generation)
    and Module IV (Execution Monitoring) downstream.

    Paper Section 3.3: the affordance result encodes all spatial
    interaction information needed to execute the task plan.
    """
    task_id: str
    task: str
    tool_name: str
    target_name: str
    keypoints: KeypointResult
    coordinates: AffordanceCoordinates
    dotted_tool_image_path: str
    dotted_target_image_path: str
    verified_tool_image_path: str
    verified_target_image_path: str
    verification_grid_path: str
